version: "3.1"
services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123654123
            TZ: America/Argentina/Buenos_Aires
        volumes:
            - ./datadb:/var/lib/mysql
        networks:
            - default

    www:
        build: .
        restart: always
        environment:
          - TZ=America/Argentina/Buenos_Aires
        ports:
            - 8080:80
        links:
            - db
        networks:
            - default